### ISSUE TITLE
Implement the requirement that a type of version bump must be specified in order for a PR to be merged

### ISSUE THREAD

**Issue by phlippieb-discovery** [phlippieb-discovery/test-podbump-on-merge#2]

**Comment by phlippieb-discovery** [comment]
This seems to be complete. To recreate:
- Create an Action [like this one](https://github.com/phlippieb-discovery/test-podbump-on-merge/edit/phlippieb-discovery-patch-1/.github/workflows/has-version-bump-label.yml)
  - This uses [required-labels](https://github.com/mheap/github-action-required-labels) from the market place
- Make the `labels` check required for the main/master branch in settings
  - Navigate to settings -> branches
  - Add or update the branch protection rule for main/master
  - Under "Require status checks...", add the `labels` check. For some reason, this was called "labels" on this repo, and not "Has version bump label"

**Comment by phlippieb-discovery** [comment]
Follow-up notes:
- The name "label" comes from the action's yaml. This commit changes it to something more descriptive, and demonstrates where the name comes from: https://github.com/phlippieb-discovery/test-podbump-on-merge/commit/26fd7886f0cface434512254f93c5d3c06cdb14f
- This allows you to have other unrelated labels (e.g. "other" in this repo). Having another label on its own won't falsely pass the check, and having another label with the required one won't falsely fail the check.

**Comment by phlippieb-discovery** [comment]
The yaml:

```yml
name: Has version-bump label
on:
  pull_request:
    types: [opened, labeled, unlabeled, synchronize]
jobs:
  label:
    runs-on: ubuntu-latest
    steps:
      - uses: mheap/github-action-required-labels@v2
        with:
          mode: exactly
          count: 1
          labels: "bump:patch, bump:minor, bump:major, bump:none"
```
